In [1]:
import os
import json
import pandas as pd
from pprint import pprint as pp
import itertools

In [2]:
keys_to_exclude = ["predictions", "labels", "generations", "unfiltered_outputs"]

In [3]:
list_files = [file_ for file_ in os.listdir("Dump/") if file_.endswith("RESULTS.json")]
json_files = []
csvs = []
for json_file in list_files:
    print(json_file)
    with open("Dump/" + json_file, "r") as f:
        js = json.load(f)
        json_files.append(js)

        for d in js:
            for key in keys_to_exclude:
                d.pop(key, None)
        df = pd.DataFrame(js, columns=js[0].keys())
        csvs.append(df)

diptanu-fBERT_SEQ_CLS_VANILLA_FT_davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism_NO-ES_RESULTS.json
diptanu-fBERT_SEQ_CLS_VANILLA_FT_hateval-immigrant-TO-waseem-racism-TO-ibereval_NO-ES_RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_AGEM_davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism_mem_size_proportion=0.01NO-ES_RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism_NO-ES_RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant_NO-ES_RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_hateval-immigrant-TO-waseem-racism-TO-ibereval_NO-ES_RESULTS.json
fBERTdavidson_ewc_lambda=2000NO-ES_RESULTS.json
fBERT_AGEM_evalita-proportion0025_RESULTS.json
fBERT_AGEM_evalita_mem_size_proportion001_RESULTS.json
fBERT_AGEM_evalita_mem_size_propor

In [4]:
# csvs[0]

In [5]:
zero_shots = pd.read_csv(r"Dump/Zero_Shots/df_plm_zero_shots.csv")

In [6]:
from continual_hate.metrics import transform_df_to_cl_metrics
from continual_hate.constants import dict_name_experiments_domain_transfer

c:\Users\alber\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
csvs[0].columns

Index(['model', 'type_experiment', 'n_trainable_params', 'cl_technique',
       'hyperparams', 'experiment_name', 'time', 'dataset_currently_testing',
       'dataset_currently_training', 'dataset_wrt_training_datasets',
       'target_epochs', 'best_epochs', 'learning_rate', 'batch_size',
       'current_num_samples_training', 'cumulative_samples_trained',
       'f1_score', 'precision_score', 'recall_score', 'accuracy',
       'HATE_f1_score', 'HATE_precision_score', 'HATE_recall_score',
       'NoHATE_f1_score', 'NoHATE_precision_score', 'NoHATE_recall_score'],
      dtype='object')

In [8]:
dfs_cl = []
for df in csvs:
    df_cl_metrics = transform_df_to_cl_metrics(df, 
                                zero_shots, 
                                performance_column="f1_score", 
                                experiment_name_column="experiment_name", 
                                dataset_test_results_column="dataset_currently_testing", 
                                dataset_current_training_column="dataset_currently_training", 
                                time_column="time",
                                model_name_column="model", 
                                dataset_dict_trainings=dict_name_experiments_domain_transfer)
    dfs_cl.append(df_cl_metrics)

    df_cl_metrics = transform_df_to_cl_metrics(df, 
                                zero_shots, 
                                performance_column="HATE_f1_score", 
                                experiment_name_column="experiment_name", 
                                dataset_test_results_column="dataset_currently_testing", 
                                dataset_current_training_column="dataset_currently_training", 
                                time_column="time",
                                model_name_column="model", 
                                dataset_dict_trainings=dict_name_experiments_domain_transfer)
    dfs_cl.append(df_cl_metrics)


Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'vanilla_ft',
 'current_num_samples_training': np.int64(4293),
 'experiment_name': 'davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism',
 'hyperparams': '',
 'learning_rate': np.float64(1e-05),
 'model': 'diptanu/fBERT',
 'time': np.int64(5)}
Experiment ->  davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism
Datasets trained ->
['davidson', 'founta_hateful_57k', 'ibereval', 'hateval-immigrant', 'hateval-women', 'waseem-racism']

Matrix Computed
[[0.91661695 0.77270589 0.61316242 0.45790817 0.34820422 0.59587484]
 [0.91297956 0.78015968 0.6265587  0.46257979 0.47471831 0.62687747]
 [0.90108164 0.72015788 0.75612445 0.41876551 0.50066344 0.59884611]
 [0.84952315 0.74882483 0.79133614 0.4

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'agem',
 'current_num_samples_training': np.int64(4799),
 'experiment_name': 'evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant',
 'hyperparams': 'mem_size_proportion=0.05',
 'learning_rate': np.float64(1e-05),
 'model': 'diptanu/fBERT',
 'time': np.int64(3)}
Experiment ->  evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
Datasets trained ->
['evalita', 'waseem-racism', 'ibereval', 'hateval-immigrant']

Matrix Computed
[[0.6611399  0.16487455 0.56126482 0.13540197]
 [0.63829787 0.69853918 0.61160714 0.14040115]
 [0.69063181 0.69724771 0.81578947 0.10134128]
 [0.71785384 0.71812081 0.8545781  0.60415557]]
Getting the zero shot array
diptanu/fBERT
evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
['evalita', 'waseem-racism', 'ibereval', 'hateval-immigran

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'agem',
 'current_num_samples_training': np.int64(4799),
 'experiment_name': 'evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant',
 'hyperparams': 'mem_size_proportion=0.025',
 'learning_rate': np.float64(1e-05),
 'model': 'FacebookAI/roberta-base',
 'time': np.int64(3)}
Experiment ->  evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
Datasets trained ->
['evalita', 'waseem-racism', 'ibereval', 'hateval-immigrant']

Matrix Computed
[[0.82635386 0.4741533  0.91066814 0.38561495]
 [0.83661713 0.84552568 0.89459995 0.52446432]
 [0.80096822 0.839491   0.93014361 0.49581838]
 [0.76199143 0.83571764 0.95083965 0.4755648 ]]
Getting the zero shot array
FacebookAI/roberta-base
evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
['evalita', 'waseem-racism', 'ibereva

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

In [9]:
df_merged_cl = pd.concat(dfs_cl)

In [10]:
df_merged_cl.sort_values(["model", "experiment_name"])

model cl_technique  \
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base   vanilla_ft   
0  FacebookAI/roberta-base   vanilla_ft   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base   vanilla_ft   
0  FacebookAI/roberta-base   vanilla_ft   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base   vanilla_ft   
0  FacebookAI/roberta-base   vanilla_ft   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0  FacebookAI/roberta-base         agem   
0          GroNLP/hateBERT   vanilla_ft   
0          GroNLP/hateBERT   vanilla_ft   
0          GroNLP/hateBERT          mas   
0          GroNLP/hateBERT          mas   
0          GroNLP/hateBERT          mas   
0          GroNLP/hateBERT          mas   
0          GroNLP/hateBERT          mas   
0          GroNLP/hateBERT          mas   
0            diptanu/fBERT   vanilla_ft   
0            diptanu/fBERT   vanilla_ft   
0            diptanu/fBERT          ewc   
0            diptanu/fBERT          ewc   
0            diptanu/fBERT          ewc   
0            diptanu/fBERT          ewc   
0            diptanu/fBERT          ewc   
0            diptanu/fBERT          ewc   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT   vanilla_ft   
0            diptanu/fBERT   vanilla_ft   
0            diptanu/fBERT   vanilla_ft   
0            diptanu/fBERT   vanilla_ft   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   
0            diptanu/fBERT         agem   

                                     experiment_name  time  best_epochs  \
0  davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0  davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0  davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0  davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0  davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0  davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0  evalita-TO-waseem-racism-TO-ibereval-TO-hateva...     3            8   
0  evalita-TO-waseem-racism-TO-ibereval-TO-hateva...     3            8   
0  evalita-TO-waseem-racism-TO-ibereval-TO-hateva...     3            8   
0  evalita-TO-waseem-racism-TO-ibereval-TO-hateva...     3            8   
0  evalita-TO-waseem-racism-TO-ibereval-TO-hateva...     3            8   
0  evalita-TO-waseem-racism-TO-ibereval-TO-hateva...     3            8   
0  evalita-TO-waseem-racism-TO-ibereval-TO-hateva...     3            8   
0  evalita-TO-waseem-racism-TO-ibereval-TO-hateva...     3            8   
0     hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0     hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0     hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0     hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0     hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0     hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0     hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0    

In [11]:
df_merged_cl.to_csv("df_cl_metrics_hyperparams.csv", index=False)