In [1]:
import os
import json
import pandas as pd
from pprint import pprint as pp
import itertools

In [2]:
keys_to_exclude = ["predictions", "labels", "generations", "unfiltered_outputs"]

In [3]:
list_files = [file_ for file_ in os.listdir("DUMP") if file_.endswith("RESULTS.json")]
json_files = []
csvs = []
for json_file in list_files:
    print(json_file)
    with open("DUMP/" + json_file, "r") as f:
        js = json.load(f)
        json_files.append(js)

        for d in js:
            for key in keys_to_exclude:
                d.pop(key, None)
        df = pd.DataFrame(js, columns=js[0].keys())
        csvs.append(df)

diptanu-fBERT_SEQ_CLS_VANILLA_FT_davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism__RESULTS.json
diptanu-fBERT_SEQ_CLS_VANILLA_FT_evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant__RESULTS.json
diptanu-fBERT_SEQ_CLS_VANILLA_FT_hateval-immigrant-TO-waseem-racism-TO-ibereval__RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism__RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant__RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_hateval-immigrant-TO-waseem-racism-TO-ibereval__RESULTS.json
fBERT_AGEM_davidson_mem_size_proportion0025_RESULTS.json
fBERT_AGEM_evalita-proportion0025_RESULTS.json
fBERT_AGEM_hatevalmem_size_proportion0025_RESULTS.json
fBERT_EWC_davidson_ewc_lambda1500_RESULTS.json
fBERT_EWC_evalita-TO-waseem_lambda1500_RESULTS.json
fBERT_EWC_hateval_ewc_la

In [4]:
# csvs[0]

In [5]:
zero_shots = pd.read_csv(r"DUMP/Zero_Shots/df_plm_zero_shots.csv")

In [6]:
from continual_hate.metrics import transform_df_to_cl_metrics
from continual_hate.constants import dict_name_experiments_domain_transfer

c:\Users\alber\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
csvs[0].columns

Index(['model', 'type_experiment', 'n_trainable_params', 'cl_technique',
       'hyperparams', 'experiment_name', 'time', 'dataset_currently_testing',
       'dataset_currently_training', 'dataset_wrt_training_datasets',
       'target_epochs', 'best_epochs', 'learning_rate', 'batch_size',
       'current_num_samples_training', 'cumulative_samples_trained',
       'best_epoch', 'f1_score', 'precision_score', 'recall_score', 'accuracy',
       'HATE_f1_score', 'HATE_precision_score', 'HATE_recall_score',
       'NoHATE_f1_score', 'NoHATE_precision_score', 'NoHATE_recall_score'],
      dtype='object')

In [8]:
dfs_cl = []
for df in csvs:
    df_cl_metrics = transform_df_to_cl_metrics(df, 
                                zero_shots, 
                                performance_column="f1_score", 
                                experiment_name_column="experiment_name", 
                                dataset_test_results_column="dataset_currently_testing", 
                                dataset_current_training_column="dataset_currently_training", 
                                time_column="time",
                                model_name_column="model", 
                                dataset_dict_trainings=dict_name_experiments_domain_transfer)
    dfs_cl.append(df_cl_metrics)

    df_cl_metrics = transform_df_to_cl_metrics(df, 
                                zero_shots, 
                                performance_column="HATE_f1_score", 
                                experiment_name_column="experiment_name", 
                                dataset_test_results_column="dataset_currently_testing", 
                                dataset_current_training_column="dataset_currently_training", 
                                time_column="time",
                                model_name_column="model", 
                                dataset_dict_trainings=dict_name_experiments_domain_transfer)
    dfs_cl.append(df_cl_metrics)



Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'vanilla_ft',
 'current_num_samples_training': np.int64(4293),
 'experiment_name': 'davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism',
 'hyperparams': '',
 'learning_rate': np.float64(1e-05),
 'model': 'diptanu/fBERT',
 'time': np.int64(5)}
Experiment ->  davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism
Datasets trained ->
['davidson', 'founta_hateful_57k', 'ibereval', 'hateval-immigrant', 'hateval-women', 'waseem-racism']

Matrix Computed
[[0.92009541 0.77163322 0.61613236 0.45396275 0.32757357 0.57422539]
 [0.92302661 0.77282148 0.61767931 0.46075257 0.37517021 0.61184926]
 [0.91008693 0.71101846 0.74700826 0.40255542 0.40389242 0.55010259]
 [0.84682134 0.74879593 0.76944444 0.4

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'ewc',
 'current_num_samples_training': np.int64(4500),
 'experiment_name': 'hateval-immigrant-TO-waseem-racism-TO-ibereval',
 'hyperparams': 'ewc_lambda=1500',
 'learning_rate': np.float64(1e-05),
 'model': 'diptanu/fBERT',
 'time': np.int64(2)}
Experiment ->  hateval-immigrant-TO-waseem-racism-TO-ibereval
Datasets trained ->
['hateval-immigrant', 'waseem-racism', 'ibereval']

Matrix Computed
[[0.61381896 0.4789357  0.50328228]
 [0.48970901 0.6878453  0.00704225]
 [0.59241706 0.68822171 0.75128645]]
Getting the zero shot array
diptanu/fBERT
hateval-immigrant-TO-waseem-racism-TO-ibereval
['hateval-immigrant', 'waseem-racism', 'ibereval']
Index(['model', 'type_experiment', 'n_trainable_params', 'cl_technique',
       'hyperparams', 'experiment_name', 'time', 'dataset_currently_

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'lwf',
 'current_num_samples_training': np.int64(4293),
 'experiment_name': 'davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism',
 'hyperparams': 'lwf_lambda=1_temperature=2',
 'learning_rate': np.float64(1e-05),
 'model': 'GroNLP/hateBERT',
 'time': np.int64(5)}
Experiment ->  davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism
Datasets trained ->
['davidson', 'founta_hateful_57k', 'ibereval', 'hateval-immigrant', 'hateval-women', 'waseem-racism']

Matrix Computed
[[0.89307129 0.67900845 0.4733501  0.39135429 0.63579208 0.55966912]
 [0.89696917 0.71276869 0.48921014 0.39507352 0.64748011 0.59218477]
 [0.89938982 0.71418211 0.69751416 0.39869776 0.65303044 0.55626933]
 [0.88502813 0.73

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'mas',
 'current_num_samples_training': np.int64(4799),
 'experiment_name': 'evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant',
 'hyperparams': 'mas_lambda=1000_mas_variation=global',
 'learning_rate': np.float64(1e-05),
 'model': 'GroNLP/hateBERT',
 'time': np.int64(3)}
Experiment ->  evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
Datasets trained ->
['evalita', 'waseem-racism', 'ibereval', 'hateval-immigrant']

Matrix Computed
[[0.69506726 0.0047619  0.78615071 0.00314465]
 [0.64112388 0.015      0.66514806 0.0031746 ]
 [0.67710843 0.02948403 0.75264271 0.00316456]
 [0.67710843 0.02948403 0.75264271 0.00316456]]
Getting the zero shot array
GroNLP/hateBERT
evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
['evalita', 'waseem-racism', 'ibereval', 'h

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]


Matrix Computed
[[0.60557769 0.36538462 0.70539419]
 [0.6074229  0.37847222 0.57352941]
 [0.6049505  0.51644336 0.71919192]]
Getting the zero shot array
FacebookAI/roberta-base
hateval-immigrant-TO-waseem-racism-TO-ibereval
['hateval-immigrant', 'waseem-racism', 'ibereval']
Index(['model', 'type_experiment', 'n_trainable_params', 'cl_technique',
       'hyperparams', 'experiment_name', 'time', 'dataset_currently_testing',
       'dataset_currently_training', 'dataset_wrt_training_datasets',
       'target_epochs', 'best_epochs', 'learning_rate', 'batch_size',
       'current_num_samples_training', 'cumulative_samples_trained',
       'f1_score', 'precision_score', 'recall_score', 'accuracy',
       'HATE_f1_score', 'HATE_precision_score', 'HATE_recall_score',
       'NoHATE_f1_score', 'NoHATE_precision_score', 'NoHATE_recall_score'],
      dtype='object')
ZERO SHOT ARRAY
                      model type_experiment  n_trainable_params  \
18  FacebookAI/roberta-base            test     

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

In [9]:
df_merged_cl = pd.concat(dfs_cl)

In [10]:
df_merged_cl.sort_values(["model", "experiment_name"])

model cl_technique  \
0   FacebookAI/roberta-base   vanilla_ft   
0   FacebookAI/roberta-base   vanilla_ft   
0   FacebookAI/roberta-base         agem   
0   FacebookAI/roberta-base         agem   
0   FacebookAI/roberta-base          ewc   
..                      ...          ...   
0             diptanu/fBERT          ewc   
0             diptanu/fBERT          lwf   
0             diptanu/fBERT          lwf   
0             diptanu/fBERT          mas   
0             diptanu/fBERT          mas   

                                      experiment_name  time  best_epochs  \
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
..                                                ...   ...          ...   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   

    current_num_samples_training  learning_rate  \
0                           4293        0.00001   
0                           4293        0.00001   
0                           4293        0.00001   
0                           4293        0.00001   
0                           4293        0.00001   
..                           ...            ...   
0                           4500        0.00001   
0                           4500        0.00001   
0                           4500        0.00001   
0                           4500        0.00001   
0                           4500        0.00001   

                             hyperparams      last  avg_incremental_f1  \
0                                         0.614581            0.762119   
0                                         0.382513            0.641329   
0              mem_size_proportion=0.025  0.670290            0.778320   
0              mem_size_proportion=0.025  0.569034            0.687862   
0                        ewc_lambda=1500  0.479855            0.714625   
..                                   ...       ...                 ...   
0                        ewc_lambda=1500  0.677308            0.626635   
0             lwf_lambda=1_temperature=2  0.679820            0.601992   
0             lwf_lambda=1_temperature=2  0.609270            0.611495   
0   mas_lambda=1000_mas_variation=global  0.612708            0.544588   
0   mas_lambda=1000_mas_variation=global  0.539551            0.561645   

    transfer       bwt  fw_transfer         metric  
0   0.757924 -0.097866     0.328523       f1_score  
0   0.610642 -0.270109    -0.047111  HATE_f1_score  
0   0.800768  0.000843     0.398261       f1_score  
0   0.713357  0.001729     0.062847  HATE_f1_score  
0   0.702756 -0.211364     0.343907       f1_score  
..       ...       ...          ...            ...  
0   0.565014 -0.010513    -0.337368  HATE_f1_score  
0   0.582733  0.012776    -0.170363       f1_score  
0   0.589286 -0.039319    -0.334105  HATE_f1_score  
0   0.531862  0.018529    -0.093670       f1_score  
0   0.572355 -0.001513    -0.171437  HATE_f1_score  

[90 rows x 14 columns]

In [11]:
df_merged_cl.to_csv("df_cl_metrics_ES.csv", index=False)