In [1]:
import os
import json
import pandas as pd
from pprint import pprint as pp
import itertools

In [2]:
keys_to_exclude = ["predictions", "labels", "generations", "unfiltered_outputs"]

In [3]:
list_files = [file_ for file_ in os.listdir("DUMP") if file_.endswith("RESULTS.json")]
json_files = []
csvs = []
for json_file in list_files:
    print(json_file)
    with open("DUMP/" + json_file, "r") as f:
        js = json.load(f)
        json_files.append(js)

        for d in js:
            for key in keys_to_exclude:
                d.pop(key, None)
        df = pd.DataFrame(js, columns=js[0].keys())
        csvs.append(df)

diptanu-fBERT_SEQ_CLS_VANILLA_FT_davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism_NO-ES_RESULTS.json
diptanu-fBERT_SEQ_CLS_VANILLA_FT_evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant_NO-ES_RESULTS.json
diptanu-fBERT_SEQ_CLS_VANILLA_FT_hateval-immigrant-TO-waseem-racism-TO-ibereval_NO-ES_RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism_NO-ES_RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant_NO-ES_RESULTS.json
FacebookAI-roberta-base_SEQ_CLS_VANILLA_FT_hateval-immigrant-TO-waseem-racism-TO-ibereval_NO-ES_RESULTS.json
fBERT_AGEM_davidson_mem_size_proportion0025_RESULTS.json
fBERT_AGEM_evalita-proportion0025_RESULTS.json
fBERT_AGEM_hatevalmem_size_proportion0025_RESULTS.json
fBERT_EWC_davidson_ewc_lambda1500_RESULTS.json
fBERT_EWC_evalita-TO-waseem_lambda1500_RESULTS

In [4]:
# csvs[0]

In [5]:
zero_shots = pd.read_csv(r"DUMP/Zero_Shots/df_plm_zero_shots.csv")

In [6]:
from continual_hate.metrics import transform_df_to_cl_metrics
from continual_hate.constants import dict_name_experiments_domain_transfer

c:\Users\alber\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
csvs[0].columns

Index(['model', 'type_experiment', 'n_trainable_params', 'cl_technique',
       'hyperparams', 'experiment_name', 'time', 'dataset_currently_testing',
       'dataset_currently_training', 'dataset_wrt_training_datasets',
       'target_epochs', 'best_epochs', 'learning_rate', 'batch_size',
       'current_num_samples_training', 'cumulative_samples_trained',
       'f1_score', 'precision_score', 'recall_score', 'accuracy',
       'HATE_f1_score', 'HATE_precision_score', 'HATE_recall_score',
       'NoHATE_f1_score', 'NoHATE_precision_score', 'NoHATE_recall_score'],
      dtype='object')

In [8]:
dfs_cl = []
for df in csvs:
    df_cl_metrics = transform_df_to_cl_metrics(df, 
                                zero_shots, 
                                performance_column="f1_score", 
                                experiment_name_column="experiment_name", 
                                dataset_test_results_column="dataset_currently_testing", 
                                dataset_current_training_column="dataset_currently_training", 
                                time_column="time",
                                model_name_column="model", 
                                dataset_dict_trainings=dict_name_experiments_domain_transfer)
    dfs_cl.append(df_cl_metrics)

    df_cl_metrics = transform_df_to_cl_metrics(df, 
                                zero_shots, 
                                performance_column="HATE_f1_score", 
                                experiment_name_column="experiment_name", 
                                dataset_test_results_column="dataset_currently_testing", 
                                dataset_current_training_column="dataset_currently_training", 
                                time_column="time",
                                model_name_column="model", 
                                dataset_dict_trainings=dict_name_experiments_domain_transfer)
    dfs_cl.append(df_cl_metrics)


Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'vanilla_ft',
 'current_num_samples_training': np.int64(4293),
 'experiment_name': 'davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism',
 'hyperparams': '',
 'learning_rate': np.float64(1e-05),
 'model': 'diptanu/fBERT',
 'time': np.int64(5)}
Experiment ->  davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism
Datasets trained ->
['davidson', 'founta_hateful_57k', 'ibereval', 'hateval-immigrant', 'hateval-women', 'waseem-racism']

Matrix Computed
[[0.91661695 0.77270589 0.61316242 0.45790817 0.34820422 0.59587484]
 [0.91297956 0.78015968 0.6265587  0.46257979 0.47471831 0.62687747]
 [0.90108164 0.72015788 0.75612445 0.41876551 0.50066344 0.59884611]
 [0.84952315 0.74882483 0.79133614 0.4

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'ewc',
 'current_num_samples_training': np.int64(4293),
 'experiment_name': 'davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism',
 'hyperparams': 'ewc_lambda=1500',
 'learning_rate': np.float64(1e-05),
 'model': 'diptanu/fBERT',
 'time': np.int64(5)}
Experiment ->  davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism
Datasets trained ->
['davidson', 'founta_hateful_57k', 'ibereval', 'hateval-immigrant', 'hateval-women', 'waseem-racism']

Matrix Computed
[[0.92138169 0.77264977 0.61785761 0.46422801 0.32808658 0.58657674]
 [0.92283835 0.77968542 0.61950314 0.46874297 0.39542424 0.61470317]
 [0.91560444 0.75180779 0.69891668 0.4591756  0.37116834 0.6133069 ]
 [0.86790959 0.76016456 0.7753

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'ewc',
 'current_num_samples_training': np.int64(4799),
 'experiment_name': 'evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant',
 'hyperparams': 'ewc_lambda=1500',
 'learning_rate': np.float64(1e-05),
 'model': 'GroNLP/hateBERT',
 'time': np.int64(3)}
Experiment ->  evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
Datasets trained ->
['evalita', 'waseem-racism', 'ibereval', 'hateval-immigrant']

Matrix Computed
[[0.69506726 0.0047619  0.78615071 0.00314465]
 [0.17624521 0.73878628 0.00704225 0.04945904]
 [0.66078431 0.72311213 0.87706422 0.14144272]
 [0.68566775 0.65302144 0.86754967 0.60727087]]
Getting the zero shot array
GroNLP/hateBERT
evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
['evalita', 'waseem-racism', 'ibereval', 'hateval-immigrant']
In

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'lwf',
 'current_num_samples_training': np.int64(4799),
 'experiment_name': 'evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant',
 'hyperparams': 'lwf_lambda=1_temperature=2',
 'learning_rate': np.float64(1e-05),
 'model': 'GroNLP/hateBERT',
 'time': np.int64(3)}
Experiment ->  evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
Datasets trained ->
['evalita', 'waseem-racism', 'ibereval', 'hateval-immigrant']

Matrix Computed
[[0.72981701 0.0131291  0.83236994 0.00628931]
 [0.56150507 0.4137931  0.58679707 0.        ]
 [0.67216981 0.37918216 0.84479371 0.00630915]
 [0.71085495 0.55380577 0.89292196 0.60098522]]
Getting the zero shot array
GroNLP/hateBERT
evalita-TO-waseem-racism-TO-ibereval-TO-hateval-immigrant
['evalita', 'waseem-racism', 'ibereval', 'hateval-imm

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

Metadata for current DF
dict_keys(['model', 'cl_technique', 'experiment_name', 'time', 'best_epochs', 'current_num_samples_training', 'learning_rate', 'hyperparams'])
{'best_epochs': np.int64(8),
 'cl_technique': 'ewc',
 'current_num_samples_training': np.int64(4293),
 'experiment_name': 'davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism',
 'hyperparams': 'ewc_lambda=1500',
 'learning_rate': np.float64(1e-05),
 'model': 'GroNLP/hateBERT',
 'time': np.int64(5)}
Experiment ->  davidson-TO-founta_hateful_57k-TO-ibereval-TO-hateval-immigrant-TO-hateval-women-TO-waseem-racism
Datasets trained ->
['davidson', 'founta_hateful_57k', 'ibereval', 'hateval-immigrant', 'hateval-women', 'waseem-racism']

Matrix Computed
[[0.82651072 0.38376384 0.18068536 0.05222734 0.60917722 0.15230461]
 [0.84688091 0.44794401 0.175      0.05810398 0.61024845 0.2       ]
 [0.82978723 0.45176849 0.81349911 0.17246175 0.64439655 0.16123499]
 [0.66425121 0.41991701 0.80

C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:198: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column].astype("category")
C:\Users\alber\Desktop\Continual Learning M-THESIS\1.5 Notebooks NSCC\continual_hate\metrics.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_zero_shots[dataset_test_results_column] = filtered_zero_shots[dataset_test_results_column]

In [9]:
df_merged_cl = pd.concat(dfs_cl)

In [10]:
df_merged_cl.sort_values(["model", "experiment_name"])

model cl_technique  \
0   FacebookAI/roberta-base   vanilla_ft   
0   FacebookAI/roberta-base   vanilla_ft   
0   FacebookAI/roberta-base         agem   
0   FacebookAI/roberta-base         agem   
0   FacebookAI/roberta-base          ewc   
..                      ...          ...   
0             diptanu/fBERT          ewc   
0             diptanu/fBERT          lwf   
0             diptanu/fBERT          lwf   
0             diptanu/fBERT          mas   
0             diptanu/fBERT          mas   

                                      experiment_name  time  best_epochs  \
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
0   davidson-TO-founta_hateful_57k-TO-ibereval-TO-...     5            8   
..                                                ...   ...          ...   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   
0      hateval-immigrant-TO-waseem-racism-TO-ibereval     2            8   

    current_num_samples_training  learning_rate  \
0                           4293        0.00001   
0                           4293        0.00001   
0                           4293        0.00001   
0                           4293        0.00001   
0                           4293        0.00001   
..                           ...            ...   
0                           4500        0.00001   
0                           4500        0.00001   
0                           4500        0.00001   
0                           4500        0.00001   
0                           4500        0.00001   

                             hyperparams      last  avg_incremental_f1  \
0                                         0.610120            0.753176   
0                                         0.380305            0.624947   
0              mem_size_proportion=0.025  0.724843            0.806614   
0              mem_size_proportion=0.025  0.652078            0.724422   
0                        ewc_lambda=1500  0.579716            0.744819   
..                                   ...       ...                 ...   
0                        ewc_lambda=1500  0.677308            0.626635   
0             lwf_lambda=1_temperature=2  0.679820            0.601992   
0             lwf_lambda=1_temperature=2  0.609270            0.611495   
0   mas_lambda=1000_mas_variation=global  0.586506            0.549735   
0   mas_lambda=1000_mas_variation=global  0.491663            0.551823   

    transfer       bwt  fw_transfer         metric  
0   0.742770 -0.115424     0.331506       f1_score  
0   0.584280 -0.289967    -0.047323  HATE_f1_score  
0   0.817026 -0.023101     0.383406       f1_score  
0   0.737754  0.003563     0.024406  HATE_f1_score  
0   0.732531 -0.139992     0.326999       f1_score  
..       ...       ...          ...            ...  
0   0.565014 -0.010513    -0.337368  HATE_f1_score  
0   0.582733  0.012776    -0.170363       f1_score  
0   0.589286 -0.039319    -0.334105  HATE_f1_score  
0   0.537181  0.006009    -0.137866       f1_score  
0   0.585329  0.008984    -0.275145  HATE_f1_score  

[90 rows x 14 columns]

In [11]:
df_merged_cl.to_csv("df_cl_metrics_NOES.csv", index=False)